main: com.gmail.markushygedombrowski.HLMine
version: "1.0"
name: HLMine
depend: [WorldGuard,WGRegionEvents,FastAsyncWorldEdit,VagtProfiler]
commands:
  createmine:
    aliases: ["replacemine", "reloadmine", "setminepoint","resetmine","deletemine","addmineblock"]
    description: "create mine"